#!/bin/bash
DOCKER_IMAGE=luizroos/gradify
USER_UID=$(id -u)
USER_GID=$(id -g)

# O primeiro argumento passado para o script será encaminhado para o Docker run
COMMAND="$1"

# Remove o primeiro argumento para que os outros possam ser passados para o contêiner
shift

if [[ "$COMMAND" == "upgrade" ]]; then  
  echo "Atualizando gradifyctl"
  docker pull $DOCKER_IMAGE > /dev/null 2>&1
else
  docker run -it --rm \
    -v "$(pwd):/project" \
    -e "HOST_USER_UID=$USER_UID" \
    -e "HOST_USER_GID=$USER_GID" \
    "$DOCKER_IMAGE" \
    $COMMAND "$@"
fi
