configVersion: 'v1'
project:
  name: 'spring-app'
  group: 'example'
  version: '0.0.1-SNAPSHOT'
  language:
    type: 'java'
    version: '21'
  repositories:
    - maven { url 'https://repo.spring.io/milestone' }
  plugins:
    - id 'java'
    - id 'org.springframework.boot' version '3.4.0' apply false
    - id 'io.spring.dependency-management' version '1.1.6' apply false
  subprojects:
    plugins: 
      - java
      - io.spring.dependency-management
    dependencies:
      - implementation 'org.springframework.boot:spring-boot-starter'
      - implementation 'org.springframework.boot:spring-boot-starter-actuator'
      - runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
      - testImplementation 'org.springframework.boot:spring-boot-starter-test'
      - testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  modules:
    - name: app-one
      type: app
      plugins: 
        - org.springframework.boot
      dependencies:
        - implementation project(':common')
        - implementation 'org.springframework.boot:spring-boot-starter-web'
    - name: app-two
      type: app
      plugins: 
        - org.springframework.boot
      dependencies:
        - implementation project(':common')
        - implementation 'org.springframework.boot:spring-boot-starter-web'
    - name: common
      type: lib
      dependencies:
      - implementation 'org.springframework.boot:spring-boot-starter'